POST https://data-doctors-puce.vercel.app/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Gyan",
    "lastName": "Prakash",
    "mobileNumber": "6206052476",
    "email": "gyanprakash2483@gmail.com",
    "password": "12345Yu890@"
}

###

POST https://data-doctors-puce.vercel.app/verifyotp HTTP/1.1
Content-Type: application/json

{
    "email": "gyanprakash2483@gmail.com",
    "otp": "838729"
}

###

POST https://data-doctors-puce.vercel.app/login HTTP/1.1
Content-Type: application/json

{
    "email": "gyanprakash2483@gmail.com",
    "password": "12345Yu890@"
}