POST https://data-doctors-puce.vercel.app/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Gyan",
    "lastName": "Prakash",
    "mobileNumber": "6206052476",
    "email": "gyanprakash2483@gmail.com",
    "password": "12345Yu890@",
    "isHealthcareProvider": false
}

###

POST https://data-doctors-puce.vercel.app/verifyotp HTTP/1.1
Content-Type: application/json

{
    "email": "gyanprakash2483@gmail.com",
    "otp": "256716"
}

###

POST https://data-doctors-puce.vercel.app/login HTTP/1.1
Content-Type: application/json

{
    "email": "gyanprakash2483@gmail.com",
    "password": "12345Yu890@"
}

###

POST https://data-doctors-puce.vercel.app/resetpassword HTTP/1.1
Content-Type: application/json

{
    "stage": "verifyownership",
    "email": "gyanprakash2483@gmail.com"
}

###

POST https://data-doctors-puce.vercel.app/resetpassword HTTP/1.1
Content-Type: application/json

{
    "stage": "password-reset",
    "email": "gyanprakash2483@gmail.com",
    "otp": "751385",
    "newpassword": "Gyan102@9384756"
}

###

POST https://data-doctors-puce.vercel.app/login HTTP/1.1
Content-Type: application/json

{
    "email": "gyanprakash2483@gmail.com",
    "password": "Gyan102@9384756"
}